export const SEARCH_VIDEO_FAIL = 'SEARCH_VIDEO_FAIL';
export const SEARCH_VIDEO_REQUEST = 'SEARCH_VIDEO_REQUEST';
export const SEARCH_VIDEO_SUCCESS = 'SELECTED_VIDEO_SUCCESS';

export const VIDEO_DETAILS_FAIL = 'VIDEO_DETAILS_FAIL';
export const VIDEO_DETAILS_REQUEST = 'VIDEO_DETAILS_REQUEST';
export const VIDEO_DETAILS_SUCCESS = 'VIDEO_DETAILS_SUCCESS';

export const RELATED_VIDEO_FAIL = 'RELATED_VIDEO_FAIL';
export const RELATED_VIDEO_REQUEST = 'RELATED_VIDEO_REQUEST';
export const RELATED_VIDEO_SUCCESS = 'RELATED_VIDEO_SUCCESS';

export const CHANNEL_VIDEO_FAIL = 'CHANNEL_VIDEO_FAIL';
export const CHANNEL_VIDEO_REQUEST = 'CHANNEL_VIDEO_REQUEST';
export const CHANNEL_VIDEO_SUCCESS = 'CHANNEL_VIDEO_SUCCESS';

export const COMMENT_LIST_FAIL = 'COMMENT_LIST_FAIL';
export const COMMENT_LIST_REQUEST = 'COMMENT_LIST_REQUEST';
export const COMMENT_LIST_SUCCESS = 'COMMENT_LIST_SUCCESS';

export const SHORT_LIST_FAIL = 'SHORT_LIST_FAIL';
export const SHORT_LIST_REQUEST = 'SHORT_LIST_REQUEST';
export const SHORT_LIST_SUCCESS = 'SHORT_LIST_SUCCESS';

export const CHANNEL_ID_FAIL = 'CHANNEL_ID_FAIL';
export const CHANNEL_ID_REQUEST = 'CHANNEL_ID_REQUEST';
export const CHANNEL_ID_SUCCESS = 'CHANNEL_ID_SUCCESS';

export const UPDATE_FIREBASE_ID = 'UPDATE_FIREBASE_ID';
export const UPDATE_AVATAR = 'UPDATE_AVATAR';

export const VIDEO_UPDATE_FAIL = 'VIDEO_UPDATE_FAIL';
export const VIDEO_UPDATE_REQUEST = 'VIDEO_UPDATE_REQUEST';
export const VIDEO_UPDATE_SUCCESS = 'VIDEO_UPDATE_SUCCESS';

export const VIDEO_COMMENT_REQUEST = 'VIDEO_COMMENT_REQUEST';
export const VIDEO_COMMENT_SUCCESS = 'VIDEO_COMMENT_SUCCESS';
export const VIDEO_COMMENT_FAILURE = 'VIDEO_COMMENT_FAILURE';

export const VIDEO_VIDEOID_REQUEST = 'VIDEO_VIDEOID_REQUEST';
export const VIDEO_VIDEOID_SUCCESS = 'VIDEO_VIDEOID_SUCCESS';
export const VIDEO_VIDEOID_FAILURE = 'VIDEO_VIDEOID_FAILURE';

export const LIBRARY_VIDEO = 'LIBRARY_VIDEO';
export const LIBRARY_LIKE = 'LIBRARY_LIKE';
export const LIBRARY_SUBRIPTS = 'LIBRARY_SUBRIPTS';
export const LIBRARY_DISLIKE = 'LIBRARY_DISLIKE';

export const VIDEO_UPLOAD_USERS = 'VIDEO_UPLOAD_USERS';

export const VIDEO_INTER = 'VIDEO_INTER';

export const HOME_VIDEOS_SUCCESS = 'HOME_VIDEOS_SUCCESS';
export const HOME_VIDEOS_FAIL = 'HOME_VIDEOS_FAIL';
export const HOME_VIDEOS_REQUEST = 'HOME_VIDEOS_REQUEST';

export const CHANGE_THEME = 'CHANGE_THEME';
